name: Continuous SBOM Upload

on:
  workflow_run:
    workflows: ["Dependabot Automerge"]
    types:
      - completed
  push:
    branches:
      - main

jobs:
  sbom_submission:
    runs-on: ubuntu-22.04
    if: >
      ${{ 
        (github.event.workflow_run.conclusion == 'success') || 
        (github.event_name == 'push') 
      }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install cdxgen CLI
        run: npm install -g @cyclonedx/cdxgen

      - name: Generate and Submit SBOM to Dependency-Track
        run: |
          cdxgen . \
            --server-url "${{ secrets.DT_SERVER_HOSTNAME }}" \
            --api-key "${{ secrets.DT_API_KEY }}" \
            --project-group "Dependency Automation" \
            --project-name "${{ github.repository }}" \
            --project-version "${{ github.ref_name }}"